---
- name: create jenkins user for swarm agents
  user:
    name: jenkins
    shell: /bin/bash
    system: yes
    home: /var/lib/jenkins

- name: download swarm client
  get_url:
    url: "{{ jenkins_swarm_client_url }}"
    dest: /opt/swarm-client.jar
    mode: '0755'

- name: create jenkins swarm agent systemd service from template
  template:
    src: jenkins-swarm-agent.service.j2
    dest: "/etc/systemd/system/jenkins-swarm-agent-{{ item }}.service"
    owner: root
    group: root
    mode: '0644'
  with_sequence: "count={{ jenkins_swarm_agent_count }}"
  notify:
    - reload systemd
    - restart jenkins-swarm-agent
