---
jenkins_swarm_agent_count: 3
jenkins_swarm_client_version: "3.27"
jenkins_swarm_client_url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/{{ jenkins_swarm_client_version }}/swarm-client-{{ jenkins_swarm_client_version }}.jar"
jenkins_master_url: "http://127.0.0.1:8080"
