---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart jenkins-swarm-agent
  systemd:
    name: "jenkins-swarm-agent-{{ item }}.service"
    state: restarted
  with_sequence: "count={{ jenkins_swarm_agent_count }}"
